# Generated by Django 3.2.9 on 2021-12-06 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='shipping_option',
            field=models.CharField(max_length=20),
        ),
    ]
