# Generated by Django 3.2.9 on 2021-12-08 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0004_alter_cart_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shipping_option',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='shipping_option',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shops.option'),
            preserve_default=False,
        ),
    ]
